on:
  push:
    branches:
      - master

name: Build and deploy Neo X Landing Page on master branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: npm install && NODE_ENV=production CI=false NODE_OPTIONS=--openssl-legacy-provider npm run build  
      - name: Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/out" # App source code path
          skip_app_build: true